name: Linux build and test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      
      - name: Debug - Build and test
        run: |
          nix run .#test -- --progress
      - name: Debug - Build and test ffi
        run: |
          nix run .#test-ffi -- --progress
      - name: ReleaseFast - Build and test
        run: |
          nix run .#test-release-fast -- --progress
      - name: ReleaseFast - Build and test ffi
        run: |
          nix run .#test-ffi-release-fast -- --progress
